---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: fail-calico-nodes
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "calico-node"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: fail-kube-dns
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "kube-dns"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: fail-nginx
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "kube-nginx"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: fail-kube-proxy
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "kube-proxy"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: fail-localdns
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "nodelocaldns"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
    ---
    apiVersion: pingcap.com/v1alpha1
    kind: PodChaos
    metadata:
      name: fail-portworx
      namespace: chaos-testing
    spec:
      action: pod-failure
      mode: one
      duration: "30s"
      selector:
        namespaces:
          - kube-system
        labelSelectors:
          "name": "portworx"
      scheduler: # scheduler rules for the running time of the chaos experiments about pods.
        cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: fail-stork
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "name": "stork"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
    ---
    apiVersion: pingcap.com/v1alpha1
    kind: PodChaos
    metadata:
      name: fail-stork-scheduler
      namespace: chaos-testing
    spec:
      action: pod-failure
      mode: one
      duration: "30s"
      selector:
        namespaces:
          - kube-system
        labelSelectors:
          "name": "stork-scheduler"
      scheduler: # scheduler rules for the running time of the chaos experiments about pods.
        cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: kill-calico-nodes
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "calico-node"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: kill-kube-dns
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "kube-dns"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: kill-nginx
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "kube-nginx"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: kill-kube-proxy
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "kube-proxy"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: kill-localdns
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "k8s-app": "nodelocaldns"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
    ---
    apiVersion: pingcap.com/v1alpha1
    kind: PodChaos
    metadata:
      name: kill-portworx
      namespace: chaos-testing
    spec:
      action: pod-kill
      mode: one
      duration: "30s"
      selector:
        namespaces:
          - kube-system
        labelSelectors:
          "name": "portworx"
      scheduler: # scheduler rules for the running time of the chaos experiments about pods.
        cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: kill-stork
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "name": "stork"
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 2m"
    ---
    apiVersion: pingcap.com/v1alpha1
    kind: PodChaos
    metadata:
      name: kill-stork-scheduler
      namespace: chaos-testing
    spec:
      action: pod-kill
      mode: one
      duration: "30s"
      selector:
        namespaces:
          - kube-system
        labelSelectors:
          "name": "stork-scheduler"
      scheduler: # scheduler rules for the running time of the chaos experiments about pods.
        cron: "@every 2m"
---
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-example
  namespace: chaos-testing
spec:
  action: corrupt
  mode: one
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "name": "portworx"
  corrupt:
    corrupt: "40"
    correlation: "25"
  duration: "10s"
  scheduler:
    cron: "@every 40s"
---
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-example
  namespace: chaos-testing
spec:
  action: corrupt
  mode: one
  selector:
    namespaces:
      - kube-system
    labelSelectors:
      "name": "stork"
  corrupt:
    corrupt: "40"
    correlation: "25"
  duration: "10s"
  scheduler:
    cron: "@every 40s"