##### Portworx PVC Snapshot
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ns.{{NAMESPACE}}-name.mysql-snapshot
  annotations:
    px/snapshot-source-pvc: mysql-data
spec:
   storageClassName: px-mysql-sc
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
---
##### Portworx Stork Snapshot
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot
spec:
  persistentVolumeClaimName: mysql-data
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: presnap-rule
rules:
- podSelector:
    app: mysql
  actions:
  - type: command
    background: true
    # this command will flush tables with read lock
    value: mysql --user=root --password=$MYSQL_ROOT_PASSWORD -Bse 'flush tables with read lock;system ${WAIT_CMD};'
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: GroupVolumeSnapshot
metadata:
  name: mysql-group-cloudsnapshot
spec:
  preSnapshotRule: presnap-rule
  pvcSelector:
    matchLabels:
      app: mysql
  options:
    portworx/snapshot-type: cloud
